import type { Mod } from './types';

export const modsData: Mod[] = [
  {
    name: 'Creation Club',
    type: 'separator',
  },
  {
    name: 'Survival Mode',
    type: 'mod',
    index: 2,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 59049,
    fileId: 244329,
    size: 5167,
  },
  {
    name: 'Saint and Seducers',
    type: 'mod',
    index: 4,
    active: true,
    size: 1092876237,
  },
  {
    name: 'Fishing',
    type: 'mod',
    index: 6,
    active: true,
    size: 377675522,
  },
  {
    name: 'Rare Curios',
    type: 'mod',
    index: 8,
    active: true,
    size: 111740475,
  },
  {
    name: 'Resource Pack',
    type: 'mod',
    index: 10,
    active: true,
    size: 916509890,
  },
  {
    name: 'Marketplace',
    type: 'mod',
    index: 12,
    active: true,
    size: 2938167,
  },
  {
    name: 'Creation Kit',
    type: 'separator',
  },
  {
    name: 'Creation Kit Platform Extended for Skyrim',
    type: 'mod',
    index: 14,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '3.5',
    modId: 71371,
    fileId: 575985,
    size: 4245464,
  },
  {
    name: 'SSE Creation Kit Fonixdata Lip Sync Fix',
    type: 'mod',
    index: 16,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 40971,
    fileId: 163332,
    size: 3729290,
  },
  {
    name: 'Skyrim Modding Essentials 2.7.1',
    type: 'separator',
  },
  {
    name: 'Script Extender',
    type: 'separator',
  },
  {
    name: 'Skyrim Script Extender (SKSE64)',
    type: 'mod',
    index: 18,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '2.2.6',
    modId: 30379,
    fileId: 462377,
    size: 751136,
  },
  {
    name: 'Skyrim Script Extender (SKSE64) - Scripts',
    type: 'mod',
    index: 20,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '2.2.6',
    modId: 30379,
    fileId: 462377,
    size: 751136,
  },
  {
    name: 'Address Library for SKSE Plugins',
    type: 'mod',
    index: 22,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '8',
    modId: 32444,
    fileId: 470707,
    size: 2412602,
  },
  {
    name: 'SKSE Preloader',
    type: 'mod',
    index: 24,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '6.1.1',
    modId: 17230,
    fileId: 181171,
    size: 206648,
  },
  {
    name: 'SkyUI',
    type: 'separator',
  },
  {
    name: 'SkyUI',
    type: 'mod',
    index: 26,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '5.2SE',
    modId: 12604,
    fileId: 35407,
    size: 2783417,
  },
  {
    name: 'Wider MCM Menu for SkyUI',
    type: 'mod',
    index: 28,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.2',
    modId: 22825,
    fileId: 112005,
    size: 59580,
  },
  {
    name: 'SkyUI - Survival Mode Integration',
    type: 'mod',
    index: 30,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.1',
    modId: 17729,
    fileId: 57227,
    size: 90639,
  },
  {
    name: 'Fix Note icon for SkyUI (SKSE64 plugin)',
    type: 'mod',
    index: 32,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.2.6',
    modId: 32561,
    fileId: 318422,
    size: 135060,
  },
  {
    name: 'SkyUI - Ghost Item Bug Fix',
    type: 'mod',
    index: 34,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 49106,
    fileId: 232098,
    size: 17333,
  },
  {
    name: 'Knotwork',
    type: 'mod',
    index: 36,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 128235,
    fileId: 592652,
    size: 5639676,
  },
  {
    name: 'Frameworks',
    type: 'separator',
  },
  {
    name: 'PapyrusUtil SE - Modders Scripting Utility Functions',
    type: 'mod',
    index: 38,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '4.4',
    modId: 13048,
    fileId: 462773,
    size: 573199,
  },
  {
    name: "powerofthree's Papyrus Extender",
    type: 'mod',
    index: 40,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '5.6.1',
    modId: 22854,
    fileId: 602547,
    size: 12601048,
  },
  {
    name: 'JContainers SE',
    type: 'mod',
    index: 42,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '4.2.3',
    modId: 16495,
    fileId: 463765,
    size: 822742,
  },
  {
    name: 'Spell Perk Item Distributor',
    type: 'mod',
    index: 44,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '6.6.2',
    modId: 36869,
    fileId: 491985,
    size: 8049961,
  },
  {
    name: 'Keyword Item Distributor',
    type: 'mod',
    index: 46,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '3.0.4',
    modId: 55728,
    fileId: 479670,
    size: 8712718,
  },
  {
    name: 'Container Item Distributor',
    type: 'mod',
    index: 48,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.4',
    modId: 99486,
    fileId: 570220,
    size: 3517012,
  },
  {
    name: 'Sound Record Distributor',
    type: 'mod',
    index: 50,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.3.0',
    modId: 77815,
    fileId: 473053,
    size: 7511719,
  },
  {
    name: 'Base Object Swapper',
    type: 'mod',
    index: 52,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '2.6.1',
    modId: 60805,
    fileId: 555251,
    size: 7514274,
  },
  {
    name: 'FormList Manipulator - FLM',
    type: 'mod',
    index: 54,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.7.1',
    modId: 74037,
    fileId: 546948,
    size: 6379690,
  },
  {
    name: 'Recursion Monitor',
    type: 'mod',
    index: 56,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.2',
    modId: 76867,
    fileId: 326984,
    size: 330414,
  },
  {
    name: 'MergeMapper',
    type: 'mod',
    index: 58,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.5.0',
    modId: 74689,
    fileId: 387258,
    size: 4061312,
  },
  {
    name: 'Scaleform Translation Plus Plus NG - Updated',
    type: 'mod',
    index: 60,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 111771,
    fileId: 471366,
    size: 4131540,
  },
  {
    name: 'Fuz Ro D-oh - Silent Voice',
    type: 'mod',
    index: 62,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '2.3',
    modId: 15109,
    fileId: 464222,
    size: 282893,
  },
  {
    name: 'Fuz Ro D-oh - Silent Voice - Settings',
    index: 64,
    type: 'mod',
    active: true,
  },
  {
    name: 'AnimObject Swapper',
    type: 'mod',
    index: 66,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.0',
    modId: 75167,
    fileId: 325663,
    size: 5147318,
  },
  {
    name: 'UIExtensions',
    type: 'mod',
    index: 68,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.2.0',
    modId: 17561,
    fileId: 55628,
    size: 459887,
  },
  {
    name: 'MCM Helper',
    type: 'mod',
    index: 70,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.4.0',
    modId: 53000,
    fileId: 452755,
    size: 6622830,
  },
  {
    name: 'Animation Frameworks',
    type: 'separator',
  },
  {
    name: 'Project New Reign - Nemesis Unlimited Behavior Engine',
    type: 'mod',
    index: 72,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.84-beta',
    modId: 60033,
    fileId: 248867,
    size: 26127652,
  },
  {
    name: 'Payload Interpreter',
    type: 'mod',
    index: 74,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.1',
    modId: 65089,
    fileId: 394150,
    size: 249760,
  },
  {
    name: 'Animation Queue Fix',
    type: 'mod',
    index: 76,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.1',
    modId: 82395,
    fileId: 348271,
    size: 128700,
  },
  {
    name: 'Paired Animation Improvements',
    type: 'mod',
    index: 78,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.1',
    modId: 99621,
    fileId: 466426,
    size: 3201979,
  },
  {
    name: 'Open Animation Replacer',
    type: 'mod',
    index: 80,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '2.0.2',
    modId: 92109,
    fileId: 518680,
    size: 8397076,
  },
  {
    name: 'Animation Motion Revolution',
    type: 'mod',
    index: 82,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.5.3',
    modId: 50258,
    fileId: 320113,
    size: 387178,
  },
  {
    name: 'Dynamic Animation Casting - NG',
    type: 'mod',
    index: 84,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '3.2.4',
    modId: 73293,
    fileId: 398206,
    size: 9185368,
  },
  {
    name: 'Utilities',
    type: 'separator',
  },
  {
    name: 'Crash Logger SSE AE VR - PDB support',
    type: 'mod',
    index: 86,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.10.0',
    modId: 59818,
    fileId: 551592,
    size: 6406847,
  },
  {
    name: 'QUI',
    type: 'mod',
    index: 88,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.3.2',
    modId: 65343,
    fileId: 330266,
    size: 586204,
  },
  {
    name: 'QUI - Unofficial Update',
    type: 'mod',
    index: 90,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.4.0',
    modId: 124796,
    fileId: 524163,
    size: 425532,
  },
  {
    name: 'QUI - Settings',
    index: 92,
    type: 'mod',
    active: true,
  },
  {
    name: 'RaceMenu',
    type: 'mod',
    index: 94,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '0.4.19.14',
    modId: 19080,
    fileId: 465102,
    size: 8631730,
  },
  {
    name: 'Where in Special Edition am I',
    type: 'mod',
    index: 96,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '2.1',
    modId: 30907,
    fileId: 218913,
    size: 3026,
  },
  {
    name: 'Optional Quick Start - SE',
    type: 'mod',
    index: 98,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.4',
    modId: 63953,
    fileId: 584778,
    size: 47040,
  },
  {
    name: 'Quest Journal Limit Bug Fixer - Recover Disappeared Quests',
    type: 'mod',
    index: 100,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.2.1',
    modId: 56130,
    fileId: 368254,
    size: 3622,
  },
  {
    name: 'Universal Unwanted Effects Clearer - Visual Effects - Imagespace Modifiers - Effect Shaders - Clairvoyance',
    type: 'mod',
    index: 102,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.3.1',
    modId: 93977,
    fileId: 409740,
    size: 5562,
  },
  {
    name: 'Essentials',
    type: 'separator',
  },
  {
    name: 'SSE Engine Fixes (skse64 plugin)',
    type: 'mod',
    index: 104,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '6.1.1',
    modId: 17230,
    fileId: 489502,
    size: 301223,
  },
  {
    name: 'Engine Fixes - Settings',
    index: 106,
    type: 'mod',
    active: true,
  },
  {
    name: "powerofthree's Tweaks",
    type: 'mod',
    index: 108,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.8.1',
    modId: 51073,
    fileId: 573995,
    size: 5711807,
  },
  {
    name: 'po3 tweaks - settings',
    index: 110,
    type: 'mod',
    active: true,
  },
  {
    name: 'SSE Display Tweaks',
    type: 'mod',
    index: 112,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.5.12',
    modId: 34705,
    fileId: 454679,
    size: 186371,
  },
  {
    name: 'SSE Display Tweaks - Settings',
    index: 114,
    type: 'mod',
    active: true,
  },
  {
    name: 'Scrambled Bugs',
    type: 'mod',
    index: 116,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '21',
    modId: 43532,
    fileId: 368378,
    size: 2009006,
  },
  {
    name: 'Scrambled Bugs - Script Effect Archetype Crash Fix',
    type: 'mod',
    index: 118,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '21',
    modId: 43532,
    fileId: 368379,
    size: 2289689,
  },
  {
    name: 'Scrambled Bugs - Vendor Respawn Fix',
    type: 'mod',
    index: 120,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '21',
    modId: 43532,
    fileId: 368380,
    size: 2315018,
  },
  {
    name: 'Papyrus Tweaks NG',
    type: 'mod',
    index: 122,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '4.1.0',
    modId: 77779,
    fileId: 362490,
    size: 4352698,
  },
  {
    name: 'Papyrus Tweaks NG - Settings',
    type: 'mod',
    index: 124,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '4.1.0',
    modId: 77779,
    fileId: 362491,
    size: 7854,
  },
  {
    name: 'Unofficial Skyrim Special Edition Patch - USSEP',
    type: 'mod',
    index: 126,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '4.2.9a',
    modId: 266,
    fileId: 598358,
    size: 160958450,
  },
  {
    name: 'Unofficial Skyrim Creation Club Content Patches',
    type: 'mod',
    index: 128,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '7.7',
    modId: 18975,
    fileId: 459390,
    size: 10566418,
  },
  {
    name: 'Survival Mode Prompt Removed',
    type: 'mod',
    index: 130,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 59049,
    fileId: 244329,
    size: 5167,
  },
  {
    name: 'Console',
    type: 'separator',
  },
  {
    name: 'More Informative Console',
    type: 'mod',
    index: 132,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.0',
    modId: 19250,
    fileId: 544360,
    size: 533718,
  },
  {
    name: 'ConsoleUtilSSE NG',
    type: 'mod',
    index: 134,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.4.0',
    modId: 76649,
    fileId: 456904,
    size: 4788619,
  },
  {
    name: 'Console Commands Extender - Anniversary Edition Update',
    type: 'mod',
    index: 136,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.11.0',
    modId: 74390,
    fileId: 457109,
    size: 301674,
  },
  {
    name: 'HelpExtender',
    type: 'mod',
    index: 138,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.2.1',
    modId: 74376,
    fileId: 457112,
    size: 228837,
  },
  {
    name: 'ConsolePlusPlus',
    type: 'mod',
    index: 140,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.3.0',
    modId: 79975,
    fileId: 449158,
    size: 3566619,
  },
  {
    name: 'Autorun',
    type: 'mod',
    index: 142,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 45451,
    fileId: 184691,
    size: 1673,
  },
  {
    name: 'Controls',
    type: 'separator',
  },
  {
    name: 'Better MessageBox Controls',
    type: 'mod',
    index: 144,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.2',
    modId: 1428,
    fileId: 11023,
    size: 17621,
  },
  {
    name: 'Better Dialogue Controls',
    type: 'mod',
    index: 146,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.2',
    modId: 1429,
    fileId: 11022,
    size: 24869,
  },
  {
    name: 'Switch Camera During Dialogue',
    type: 'mod',
    index: 148,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 95269,
    fileId: 409386,
    size: 2446,
  },
  {
    name: 'Auto Input Switch',
    type: 'mod',
    index: 150,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.2.0',
    modId: 54309,
    fileId: 452745,
    size: 2246673,
  },
  {
    name: 'NVIDIA Reflex Support',
    type: 'mod',
    index: 152,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.2',
    modId: 74498,
    fileId: 353518,
    size: 5173065,
  },
  {
    name: 'Better AltTab',
    type: 'mod',
    index: 154,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 121342,
    fileId: 515927,
    size: 5206070,
  },
  {
    name: 'Media Keys Fix SKSE',
    type: 'mod',
    index: 156,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 92948,
    fileId: 503665,
    size: 142835,
  },
  {
    name: 'Kill Caps Lock NG',
    type: 'mod',
    index: 158,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 99090,
    fileId: 420132,
    size: 235809,
  },
  {
    name: 'Mute On Focus Loss',
    type: 'mod',
    index: 160,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '2',
    modId: 130163,
    fileId: 561576,
    size: 7636,
  },
  {
    name: 'Modern Toggle Walk-Run Fix 1.6.1130 and newer',
    type: 'mod',
    index: 162,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 116439,
    fileId: 489659,
    size: 3187,
  },
  {
    name: 'First Person Sneak Strafe-Walk Stutter Fix',
    type: 'mod',
    index: 164,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 31165,
    fileId: 117079,
    size: 1941,
  },
  {
    name: 'Sprint Sneak Movement Speed Fix',
    type: 'mod',
    index: 166,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.1',
    modId: 86631,
    fileId: 450440,
    size: 182899,
  },
  {
    name: 'General Fixes',
    type: 'separator',
  },
  {
    name: 'Keywords Fixed',
    type: 'mod',
    index: 168,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1',
    modId: 21597,
    fileId: 134154,
    size: 34264,
  },
  {
    name: 'Modern Brawl Bug Fix',
    type: 'mod',
    index: 170,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.4',
    modId: 1473,
    fileId: 1552,
    size: 5445,
  },
  {
    name: "Labyrinthian Shalidor's Maze Fixes",
    type: 'mod',
    index: 172,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.3',
    modId: 52239,
    fileId: 214147,
    size: 886246,
  },
  {
    name: 'dunPOISoldiersRaidOnStart Script Tweak',
    type: 'mod',
    index: 174,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 62925,
    fileId: 260981,
    size: 27302,
  },
  {
    name: 'Lights Out. Solitude Lighthouse Fix',
    type: 'mod',
    index: 176,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 34976,
    fileId: 135246,
    size: 25395,
  },
  {
    name: 'College of Winterhold Quest Start Fixes',
    type: 'mod',
    index: 178,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.4',
    modId: 53817,
    fileId: 303446,
    size: 6406,
  },
  {
    name: 'Proving Honor Companions Quest Progression Fix',
    type: 'mod',
    index: 180,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 66128,
    fileId: 275418,
    size: 2404,
  },
  {
    name: 'Source of Stalhrim Quest Fix',
    type: 'mod',
    index: 182,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 32329,
    fileId: 122547,
    size: 1417,
  },
  {
    name: 'Mount Anthor Dragon Fix',
    type: 'mod',
    index: 184,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.3',
    modId: 38510,
    fileId: 203001,
    size: 24666,
  },
  {
    name: 'Hearthfires Houses Building Fix',
    type: 'mod',
    index: 186,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.1',
    modId: 27298,
    fileId: 511094,
    size: 244303,
  },
  {
    name: 'Chillwind Depths CTD Fix',
    type: 'mod',
    index: 188,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.1',
    modId: 44249,
    fileId: 207969,
    size: 2178,
  },
  {
    name: 'Stamina of Steeds',
    type: 'mod',
    index: 190,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 58742,
    fileId: 242776,
    size: 1688,
  },
  {
    name: 'Universal Cured Serana Eye Fix',
    type: 'mod',
    index: 192,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.4',
    modId: 74759,
    fileId: 386576,
    size: 1569,
  },
  {
    name: 'Ore Vein Texture Fix',
    type: 'mod',
    index: 194,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 72638,
    fileId: 304450,
    size: 1730,
  },
  {
    name: 'Dwemer Ballista Crash fix',
    type: 'mod',
    index: 196,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 73859,
    fileId: 309757,
    size: 370,
  },
  {
    name: 'Rock Traps Trigger Fixes',
    type: 'mod',
    index: 198,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.2',
    modId: 81587,
    fileId: 512888,
    size: 767297,
  },
  {
    name: 'Green Water Cubemap Fix',
    type: 'mod',
    index: 200,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.1',
    modId: 95678,
    fileId: 406388,
    size: 262,
  },
  {
    name: 'Zero Bounty Hostility Fix',
    type: 'mod',
    index: 202,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.3',
    modId: 95989,
    fileId: 460834,
    size: 1732,
  },
  {
    name: 'Shoeless Bandit Fix',
    type: 'mod',
    index: 204,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 99465,
    fileId: 421489,
    size: 348,
  },
  {
    name: 'Fish Plaque Fixes and Improvements',
    type: 'mod',
    index: 206,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.2',
    modId: 93868,
    fileId: 401477,
    size: 7236,
  },
  {
    name: "Arcane Blacksmith's Apron - Hood Fixes",
    type: 'mod',
    index: 208,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 78927,
    fileId: 529887,
    size: 842707,
  },
  {
    name: 'CC Horse Armor Stays Token',
    index: 210,
    type: 'mod',
    active: false,
  },
  {
    name: 'Staves (Creation) - Minor Fixes',
    index: 212,
    type: 'mod',
    active: false,
  },
  {
    name: 'Script Fixes',
    type: 'separator',
  },
  {
    name: 'WIDeadBodyCleanupScript Crash Fix',
    type: 'mod',
    index: 214,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.3',
    modId: 62413,
    fileId: 523489,
    size: 2501,
  },
  {
    name: 'Simply Optimized Scripts',
    type: 'mod',
    index: 216,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.1',
    modId: 97155,
    fileId: 498293,
    size: 50190,
  },
  {
    name: 'World Encounter Hostility Fix',
    type: 'mod',
    index: 218,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.4',
    modId: 91403,
    fileId: 396164,
    size: 7524,
  },
  {
    name: 'MQ104PlayerScript Fix',
    type: 'mod',
    index: 220,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.2',
    modId: 90996,
    fileId: 387832,
    size: 2170,
  },
  {
    name: "Serana's Hood Fix",
    type: 'mod',
    index: 222,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '3.1.0',
    modId: 20243,
    fileId: 217670,
    size: 13192,
  },
  {
    name: 'High Gate Ruins Puzzle Reset Fix',
    type: 'mod',
    index: 224,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.3',
    modId: 53643,
    fileId: 392209,
    size: 2290,
  },
  {
    name: 'Mage Armor Script Fix',
    type: 'mod',
    index: 226,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 58862,
    fileId: 243411,
    size: 1471,
  },
  {
    name: 'WE05 Script Fix',
    type: 'mod',
    index: 228,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.1',
    modId: 49851,
    fileId: 203176,
    size: 1690,
  },
  {
    name: "King Olaf's Fire Festival Not Ending Fix",
    type: 'mod',
    index: 230,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.1',
    modId: 65849,
    fileId: 274311,
    size: 1635,
  },
  {
    name: 'Magic Student (WIChangeLocation04) Quest Fix',
    type: 'mod',
    index: 232,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.1',
    modId: 80676,
    fileId: 340731,
    size: 1606,
  },
  {
    name: 'Scare my Enemy Bug Fix',
    type: 'mod',
    index: 234,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 44685,
    fileId: 181189,
    size: 627,
  },
  {
    name: 'Modern Clap Bug Fix',
    type: 'mod',
    index: 236,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1',
    modId: 38621,
    fileId: 152011,
    size: 1379,
  },
  {
    name: 'CritterSpawn Congestion Fix',
    type: 'mod',
    index: 238,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.52',
    modId: 67276,
    fileId: 484532,
    size: 8054,
  },
  {
    name: 'Dragonactorscript infinite loop fix',
    type: 'mod',
    index: 240,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.3.2',
    modId: 87940,
    fileId: 588864,
    size: 12628,
  },
  {
    name: "Neloth's Experimental Subject Quest (DLC2TTR4a) Fix",
    type: 'mod',
    index: 242,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.1',
    modId: 64016,
    fileId: 265836,
    size: 1049,
  },
  {
    name: 'Bone Wolf Shutdown Fix',
    type: 'mod',
    index: 244,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 87339,
    fileId: 369942,
    size: 1979,
  },
  {
    name: 'Texture & Mesh Fixes',
    type: 'separator',
  },
  {
    name: 'Assorted mesh fixes',
    type: 'mod',
    index: 246,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.90',
    modId: 32117,
    fileId: 583110,
    size: 36114618,
  },
  {
    name: 'Floating Ash Pile Fix',
    type: 'mod',
    index: 248,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.2',
    modId: 63434,
    fileId: 264466,
    size: 20681,
  },
  {
    name: 'Skyrim Ultimate Eye Meshes Ruhmastered',
    type: 'mod',
    index: 250,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: 'v3.0',
    modId: 18147,
    fileId: 117237,
    size: 17740,
  },
  {
    name: 'Skyrim Ultimate Eye Meshes Ruhmastered - Simple Vampire Fixes SSE',
    type: 'mod',
    index: 252,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: 'v3.0',
    modId: 18147,
    fileId: 117238,
    size: 874,
  },
  {
    name: 'Eyes AO Clipping Fix',
    type: 'mod',
    index: 254,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.3',
    modId: 25753,
    fileId: 92806,
    size: 11820,
  },
  {
    name: 'Whiterun Fence Base Seam Fix',
    type: 'mod',
    index: 256,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 79337,
    fileId: 334169,
    size: 9589,
  },
  {
    name: 'Ore Vein Cube Map and Shader Fixes',
    type: 'mod',
    index: 258,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 85641,
    fileId: 362736,
    size: 70386,
  },
  {
    name: 'Sound Hammering Sounds',
    type: 'mod',
    index: 260,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 5592,
    fileId: 12403,
    size: 5764,
  },
  {
    name: 'SSS-CT - Slaughterfish Stay Submerged - Collision Tweak',
    type: 'mod',
    index: 262,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 69570,
    fileId: 290660,
    size: 2894,
  },
  {
    name: 'Spiders of Solstheim - Transparency Fix',
    type: 'mod',
    index: 264,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.1',
    modId: 60012,
    fileId: 248753,
    size: 985513,
  },
  {
    name: 'Farm Hat 01 Clipping Fix',
    type: 'mod',
    index: 266,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1',
    modId: 72213,
    fileId: 343719,
    size: 24672,
  },
  {
    name: "Guild Master's Armor First Person Texture Fix",
    type: 'mod',
    index: 268,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 75321,
    fileId: 316031,
    size: 61658,
  },
  {
    name: 'Glowing Mushroom Collision Fixes',
    type: 'mod',
    index: 270,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.2.0',
    modId: 69558,
    fileId: 472102,
    size: 7069234,
  },
  {
    name: 'Blackreach Tentacle Mesh Fix',
    type: 'mod',
    index: 272,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.1',
    modId: 43083,
    fileId: 173163,
    size: 48873,
  },
  {
    name: "Wiseman303's Flora Fixes - Revamped",
    type: 'mod',
    index: 274,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '3.2',
    modId: 28197,
    fileId: 194797,
    size: 619958,
  },
  {
    name: 'Creep Cluster Collision Fixes',
    type: 'mod',
    index: 276,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.0',
    modId: 93260,
    fileId: 411022,
    size: 84837,
  },
  {
    name: 'No More Swimming In Air - Fixed Floating SwimIdle',
    type: 'mod',
    index: 278,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 73421,
    fileId: 307745,
    size: 15694,
  },
  {
    name: 'Load Screen Shading Fix',
    type: 'mod',
    index: 280,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '0.2',
    modId: 98647,
    fileId: 453752,
    size: 30571988,
  },
  {
    name: 'Vampire Loading Screen Eye Fix',
    type: 'mod',
    index: 282,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 98187,
    fileId: 418574,
    size: 212598,
  },
  {
    name: 'Death Hound Loading Screen Eye Fix',
    type: 'mod',
    index: 284,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 98210,
    fileId: 416562,
    size: 72836,
  },
  {
    name: 'Nix-Hound Eyes Fix (Creation Club Nixhound Patch)',
    type: 'mod',
    index: 286,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 22480,
    fileId: 77742,
    size: 274410,
  },
  {
    name: 'SKSE Plugin Fixes',
    type: 'separator',
  },
  {
    name: 'Save Unbaker',
    type: 'mod',
    index: 288,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.4',
    modId: 85565,
    fileId: 363731,
    size: 3919931,
  },
  {
    name: 'Bug Fixes SSE',
    type: 'mod',
    index: 290,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '10',
    modId: 33261,
    fileId: 368384,
    size: 1862966,
  },
  {
    name: 'Barter Limit Fix',
    type: 'mod',
    index: 292,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 77173,
    fileId: 324312,
    size: 801227,
  },
  {
    name: 'Equip Enchantment Fix',
    type: 'mod',
    index: 294,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.3.6',
    modId: 42839,
    fileId: 450462,
    size: 196742,
  },
  {
    name: 'RemoveAllItems Freeze Fix',
    type: 'mod',
    index: 296,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.0',
    modId: 90734,
    fileId: 408042,
    size: 5479943,
  },
  {
    name: 'Actor Limit Fix',
    type: 'mod',
    index: 298,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '9',
    modId: 32349,
    fileId: 368385,
    size: 1851769,
  },
  {
    name: 'NPC AI Process Position Fix - NG',
    type: 'mod',
    index: 300,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.1',
    modId: 69326,
    fileId: 324089,
    size: 5497524,
  },
  {
    name: 'Animated Static Reload Fix - NG',
    type: 'mod',
    index: 302,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.1',
    modId: 69331,
    fileId: 335899,
    size: 4975755,
  },
  {
    name: 'Dual Casting Fix',
    type: 'mod',
    index: 304,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 92454,
    fileId: 393174,
    size: 3983345,
  },
  {
    name: 'Face Discoloration Fix',
    type: 'mod',
    index: 306,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.3',
    modId: 42441,
    fileId: 319047,
    size: 2285539,
  },
  {
    name: 'Combat Music Fix NG Updated',
    type: 'mod',
    index: 308,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.0',
    modId: 110459,
    fileId: 466385,
    size: 3031692,
  },
  {
    name: 'Sound Fix for Large Sector Drives',
    type: 'mod',
    index: 310,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '4',
    modId: 71567,
    fileId: 322907,
    size: 5167,
  },
  {
    name: 'Camera Persistence Fixes',
    type: 'mod',
    index: 312,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 94490,
    fileId: 548911,
    size: 5703982,
  },
  {
    name: 'DPI Scaling Fix',
    type: 'mod',
    index: 314,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 95740,
    fileId: 406607,
    size: 4192908,
  },
  {
    name: 'Mfg Fix',
    type: 'mod',
    index: 316,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.6.1',
    modId: 11669,
    fileId: 320400,
    size: 137416,
  },
  {
    name: 'Aurora Fix',
    type: 'mod',
    index: 318,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.1',
    modId: 77834,
    fileId: 327652,
    size: 5318489,
  },
  {
    name: 'Alchemy XP Fix',
    type: 'mod',
    index: 320,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 117389,
    fileId: 493497,
    size: 4706936,
  },
  {
    name: 'Bound Weapon Fix',
    type: 'mod',
    index: 322,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 134772,
    fileId: 565653,
    size: 279689,
  },
  {
    name: 'LeveledList Crash Fix',
    type: 'mod',
    index: 324,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 129136,
    fileId: 552464,
    size: 3615589,
  },
  {
    name: 'SKSE Plugins Tweaks',
    type: 'separator',
  },
  {
    name: 'Regular Quicksave for System Menu for 1.6.1170',
    type: 'mod',
    index: 326,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 131701,
    fileId: 552945,
    size: 3170912,
  },
  {
    name: 'Enhanced Invisibility',
    type: 'mod',
    index: 328,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.3.0',
    modId: 61950,
    fileId: 323345,
    size: 4760772,
  },
  {
    name: 'Enhanced Invisibility - Settings',
    type: 'mod',
    index: 330,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.3.0',
    modId: 61950,
    fileId: 323345,
    size: 4760772,
  },
  {
    name: 'Enhanced Reanimation',
    type: 'mod',
    index: 332,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.5.1',
    modId: 43500,
    fileId: 323574,
    size: 4844025,
  },
  {
    name: 'Enhanced Reanimation - Settings',
    type: 'mod',
    index: 334,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.5.1',
    modId: 43500,
    fileId: 323574,
    size: 4844025,
  },
  {
    name: 'Exit Sneak On Sprint',
    type: 'mod',
    index: 336,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1',
    modId: 138669,
    fileId: 584283,
    size: 323716,
  },
  {
    name: 'ImGui Icons',
    type: 'mod',
    index: 338,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 114790,
    fileId: 483279,
    size: 439651,
  },
  {
    name: 'PhotoMode',
    type: 'mod',
    index: 340,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.2.0',
    modId: 91701,
    fileId: 575956,
    size: 18142298,
  },
  {
    name: 'Locked Empty Container Activate Text Fix',
    type: 'mod',
    index: 342,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 99441,
    fileId: 421400,
    size: 3438621,
  },
  {
    name: 'Shadow Boost',
    type: 'mod',
    index: 344,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.3.0',
    modId: 73133,
    fileId: 350765,
    size: 5192121,
  },
  {
    name: 'Maps & Markers',
    type: 'separator',
  },
  {
    name: 'Unique Map Weather',
    type: 'mod',
    index: 346,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.1',
    modId: 59919,
    fileId: 358458,
    size: 4851520,
  },
  {
    name: 'HD Local Map',
    type: 'mod',
    index: 348,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.2',
    modId: 74722,
    fileId: 545764,
    size: 5684478,
  },
  {
    name: 'Widescreen Support',
    type: 'separator',
  },
  {
    name: 'Complete Widescreen Fix - 21-9 - Reinstall to select for your mods',
    type: 'mod',
    index: 350,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '2.0',
    modId: 1778,
    fileId: 514607,
    size: 51777147,
  },
  {
    name: 'LOD Resources',
    type: 'separator',
  },
  {
    name: 'DynDOLOD Resources SE',
    type: 'mod',
    index: 352,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: 'Alpha-45',
    modId: 52897,
    fileId: 598290,
    size: 68206603,
  },
  {
    name: 'DynDOLOD DLL SE - Scripts and DLL',
    type: 'mod',
    index: 354,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '2.82.8',
    modId: 57264,
    fileId: 495330,
    size: 28669,
  },
  {
    name: 'DynDOLOD DLL NG and Scripts 3.00',
    type: 'mod',
    index: 356,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: 'Alpha-12',
    modId: 97720,
    fileId: 550668,
    size: 4190701,
  },
  {
    name: 'xLODGen Resource - SSE Terrain Tamriel',
    type: 'mod',
    index: 358,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '2.0',
    modId: 54680,
    fileId: 401159,
    size: 17372999,
  },
  {
    name: 'ENB',
    type: 'separator',
  },
  {
    name: 'KiLoader for Skyrim',
    type: 'mod',
    index: 360,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.6',
    modId: 99404,
    fileId: 491966,
    size: 597435,
  },
  {
    name: 'ENB Binaries',
    index: 362,
    type: 'mod',
    active: false,
  },
  {
    name: 'ENB Helper SE Updated',
    type: 'mod',
    index: 364,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '2.3.0',
    modId: 110782,
    fileId: 467389,
    size: 269129,
  },
  {
    name: 'ENB Helper Plus',
    type: 'mod',
    index: 366,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.4',
    modId: 62743,
    fileId: 327653,
    size: 4805887,
  },
  {
    name: 'ENB Extender for Skyrim',
    type: 'mod',
    index: 368,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.3',
    modId: 99406,
    fileId: 596064,
    size: 343388,
  },
  {
    name: 'ENB Light Detection Fix',
    type: 'mod',
    index: 370,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 107693,
    fileId: 454885,
    size: 5204683,
  },
  {
    name: 'ENB Input Disabler',
    type: 'mod',
    index: 372,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.3',
    modId: 62796,
    fileId: 497176,
    size: 5371501,
  },
  {
    name: 'Particle Patch for ENB',
    type: 'mod',
    index: 374,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.2.6',
    modId: 65720,
    fileId: 567284,
    size: 237233027,
  },
  {
    name: 'Fixed Skeever Dinner Meshes for Skyrim Particle Patch',
    type: 'mod',
    index: 376,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1',
    modId: 68481,
    fileId: 295519,
    size: 81698,
  },
  {
    name: 'Ghost Pile Seam Fix (Skyrim Particle Patch)',
    type: 'mod',
    index: 378,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 67841,
    fileId: 282707,
    size: 825274,
  },
  {
    name: 'Word Wall Transparency Fix for ENB',
    type: 'mod',
    index: 380,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '0.3',
    modId: 41463,
    fileId: 417521,
    size: 838469,
  },
  {
    name: 'Community Shaders',
    type: 'separator',
  },
  {
    name: 'Community Shaders',
    type: 'mod',
    index: 382,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '0.6.6',
    modId: 86492,
    fileId: 588098,
    size: 36601317,
  },
  {
    name: 'Auto Parallax',
    type: 'mod',
    index: 384,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.27',
    modId: 79473,
    fileId: 336006,
    size: 5028558,
  },
  {
    name: 'Grass Lighting',
    type: 'mod',
    index: 386,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.3.2',
    modId: 86502,
    fileId: 569735,
    size: 813,
  },
  {
    name: 'Grass Collision',
    type: 'mod',
    index: 388,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.0',
    modId: 87816,
    fileId: 569736,
    size: 723,
  },
  {
    name: 'Screen Space Shadows',
    type: 'mod',
    index: 390,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.0',
    modId: 93209,
    fileId: 584193,
    size: 9312,
  },
  {
    name: 'Light Limit Fix',
    type: 'mod',
    index: 392,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.2',
    modId: 99548,
    fileId: 569998,
    size: 4261,
  },
  {
    name: 'Subsurface Scattering',
    type: 'mod',
    index: 394,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 114114,
    fileId: 569737,
    size: 3478,
  },
  {
    name: 'Wetness Effects',
    type: 'mod',
    index: 396,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 112739,
    fileId: 569738,
    size: 3653,
  },
  {
    name: 'Water Effects',
    type: 'mod',
    index: 398,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 112762,
    fileId: 569739,
    size: 39082,
  },
  {
    name: 'Terrain Shadows',
    type: 'mod',
    index: 400,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 135817,
    fileId: 570047,
    size: 2408,
  },
  {
    name: 'Terrain Shadows - Vanilla Heightmaps',
    type: 'mod',
    index: 402,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 135817,
    fileId: 570012,
    size: 14580597,
  },
  {
    name: 'Screen Space Global Illumination (SSGI)',
    type: 'mod',
    index: 404,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '3.0.0',
    modId: 130375,
    fileId: 573336,
    size: 2688640,
  },
  {
    name: 'Cloud Shadows',
    type: 'mod',
    index: 406,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.1.1',
    modId: 139185,
    fileId: 584194,
    size: 749,
  },
  {
    name: 'Skylighting',
    type: 'mod',
    index: 408,
    active: false,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.1',
    modId: 139352,
    fileId: 584845,
    size: 3213397,
  },
  {
    name: 'Animations',
    type: 'separator',
  },
  {
    name: 'First Person Animation Teleport Bug Fix',
    type: 'mod',
    index: 410,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.0',
    modId: 92795,
    fileId: 395075,
    size: 3742,
  },
  {
    name: 'Horse Mount and Dismount Double Sound Fix',
    type: 'mod',
    index: 412,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0.1',
    modId: 99621,
    fileId: 466552,
    size: 27423,
  },
  {
    name: 'Assorted Animation Fixes',
    type: 'mod',
    index: 414,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '1.0',
    modId: 93271,
    fileId: 416390,
    size: 317384,
  },
  {
    name: 'Bodyslide',
    type: 'separator',
  },
  {
    name: 'BodySlide and Outfit Studio',
    type: 'mod',
    index: 416,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '5.6.3',
    modId: 201,
    fileId: 549611,
    size: 12742587,
  },
  {
    name: 'Outputs',
    type: 'separator',
  },
  {
    name: 'Synthesis Output',
    index: 418,
    type: 'mod',
    active: true,
  },
  {
    name: 'SME Modgroups',
    index: 420,
    type: 'mod',
    active: true,
  },
  {
    name: 'SME Patches',
    index: 422,
    type: 'mod',
    active: true,
  },
  {
    name: 'SME - Nemesis Output',
    type: 'mod',
    index: 424,
    active: true,
    gameName: 'SkyrimSpecialEdition',
    version: '6.1.1',
    modId: 17230,
    fileId: 489502,
    size: 301223,
  },
];
